-- Initial Database Schema for Starlite Blog
-- This file is for reference - Prisma will handle migrations automatically

-- Create database (run manually if needed)
-- CREATE DATABASE starliteblog;

-- Note: The actual schema will be generated by Prisma migrations
-- Run: npx prisma migrate dev --name init

-- This file serves as documentation of the initial schema structure
/*
Tables to be created by Prisma:
- users
- categories  
- tags
- posts
- post_categories (junction table)
- post_tags (junction table)
- media
- post_analytics
- newsletter_subscribers
*/